import Navigation from "@/components/layout/Navigation";
import MapWrapper from "@/components/map/MapWrapper";
import ChatIdProvider from "@/components/provider/ChatIdProvider";
import RQProvider from "@/components/provider/RQProvider";
import { ThemeProvider } from "@/components/provider/theme-provider";
import type { Metadata } from "next";
import { Nanum_Gothic } from "next/font/google";
import "../globals.css";
// TODO: APP키 환경변수 적용

declare global {
  interface Window {
    kakao: any;
  }
}

const nanum = Nanum_Gothic({
  subsets: ["latin"],
  weight: ["400", "700", "800"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="ko">
      <body
        className={`${nanum.className} flex text-black dark:text-grey mo:flex-col-reverse mo:h-screen mo:bg-neutral-800`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <RQProvider>
            <ChatIdProvider>
              <Navigation />
              {children}
              <MapWrapper />
            </ChatIdProvider>
          </RQProvider>
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
