import Navigation from "@/components/layout/Navigation";
import Map from "@/components/map/Map";
import RQProvider from "@/components/provider/RQProvider";
import type { Metadata } from "next";
import { Nanum_Gothic } from "next/font/google";
import Script from "next/script";
import "../globals.css";
// TODO: APP키 환경변수 적용

declare global {
  interface Window {
    kakao: any;
  }
}

const nanum = Nanum_Gothic({
  subsets: ["latin"],
  weight: ["400", "700", "800"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="ko">
      <head>
        <script
          src={`//dapi.kakao.com/v2/maps/sdk.js?appkey=dfdebaf84d7dda475fb8448c7d43c528&libraries=clusterer,services`}
        />
      </head>
      <body
        className={`${nanum.className} flex text-grey mo:flex-col-reverse mo:h-screen mo:bg-neutral-800`}
      >
        <RQProvider>
          <Navigation />
          {children}
          <Map />
        </RQProvider>
      </body>
    </html>
  );
};

export default RootLayout;
